### PR TITLE
V0.10.0

### PR DESCRIPTION
**Pull request by caoxiemeihao**
#### Break!

This is a redesigned version of the API<sub><sup>(Only 3 APIs)</sub></sup>. Not compatible with previous versions!

```ts
export type Configuration = {
  /**
   * Shortcut of `build.lib.entry`
   */
  entry?: import('vite').LibraryOptions['entry']
  /**
   * Triggered when Vite is built.  
   * If passed this parameter will not automatically start Electron App.  
   * You can start Electron App through the `startup` function passed through the callback function.  
   */
  onstart?: (this: import('rollup').PluginContext, startup: (args?: string[]) => Promise<void>) => void
  vite?: import('vite').InlineConfig
}
```

In the past few weeks, some issues have been mentioned in many issues that cannot be solved amicably. So I refactored the API to avoid design flaws. But despite this, the new version will only be easier rather than harder.

For example, some common problems in the following issues.

#### Multiple entry files is not support #86

  Thanks to Vite@3.2.0's `lib.entry` supports multiple entries, which makes the configuration of the new version very simple. **So the `vite-plugin-electron@0.10.0` requires Vite at least `v3.2.0`**.

  **e.g.**

  ```ts
  import electron from 'vite-plugin-electron'

  // In plugins option
  electron({
    entry: [
      'electron/entry-1.ts',
      'electron/entry-2.ts',
    ],
  })

  // Or use configuration array
  electron([
    {
      entry: [
        'electron/entry-1.ts',
        'electron/entry-2.ts',
      ],
    },
    {
      entry: 'foo/bar.ts',
    },
  ])
  ```

#### require is not defined #48, #87

  `vite-plugin-electron-renderer` will change `output.format` to `cjs` format by default<sub><sup>(This is because currently Electron@21 only supports CommonJs)</sub></sup>, which will cause the built code to use `require` to import modules, if the user `nodeIntegration` is not enabled in the Electron-Main process which causes the error `require is not defined` to be thrown.

  `vite-plugin-electron-renderer@0.10.0` provides the `nodeIntegration` option. It is up to the user to decide whether to use Node.js(CommonJs).

  **e.g.**

  ```ts
  import renderer from 'vite-plugin-electron-renderer'

  // In plugins option
  renderer({
    nodeIntegration: true,
  })
  ```

#### Use `Worker` in Electron-Main or Electron-Renderer #77, #81

> You can see 👉 [examples/worker](https://github.com/caoxiemeihao/vite-plugin-electron/tree/main/examples/worker)

- Use Worker in Electron-Main

  **e.g.** <sub><sup>This looks the same as multiple entry</sub></sup>

  ```ts
  import electron from 'vite-plugin-electron'

  // In plugins option
  electron({
    entry: [
      'electron/main.ts',
      'electron/worker.ts',
    ],
  })

  // In electron/main.ts
  new Worker(path.join(__dirname, './worker.js'))
  ```

- Use Worker in Electron-Renderer

  **e.g.**

  ```ts
  import renderer, { worker } from 'vite-plugin-electron-renderer'

  export default {
    plugins: [
      renderer({
        // If you need use Node.js in Electron-Renderer process
        nodeIntegration: true,
      }),
    ],
    worker: {
      plugins: [
        worker({
          // If you need use Node.js in Worker
          nodeIntegrationInWorker: true,
        }),
      ],
    },
  }
  ```

#### TODO

- [ ] There is no way to differentiate between Preload-Scripts, which will cause the entire Electron App to restart after the preload update, not the Electron-Renderer reload.

### CODE REVIEW

**Comment by caoxiemeihao** [comment]
@astoilkov @jooy2 Hi here! 👋
`v0.10.0` is coming, seems reasonable?

**Comment by jooy2** [comment]
Thanks for the quick update!
I'll try it as soon as Vite 3.2.0 is released. I can't seem to try it right now because of a Dependency conflict.
(This also happens in Vite 3.2.0-beta0.)

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: myProject@1.8.5
npm ERR! Found: vite@3.1.6
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.1.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@">=3.2.0" from vite-plugin-electron@0.10.0
npm ERR! node_modules/vite-plugin-electron
npm ERR!   dev vite-plugin-electron@"0.10.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.       
npm ERR!
npm ERR! See C:\Users\user\AppData\Local\npm-cache\eresolve-report.txt for a full rep
ort.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2022-10-10T04_47_39_548Z-deb
ug-0.log

For more detail, add `--debug` to the command
```

**Comment by astoilkov** [comment]
## The change to `cjs` format

What happens with `await import('./path')` calls? What are they transformed to and are they still async?

## Worker change

Is it going to be possible to create a new Worker with `URL` and `type: 'module'`?

```ts
new Worker(new URL('./worker', import.meta.url), {
  type: 'module'
})
```

**Comment by caoxiemeihao** [comment]
@jooy2 
> Thanks for the quick update!
I'll try it as soon as Vite 3.2.0 is released. I can't seem to try it right now because of a Dependency conflict.
(This also happens in Vite 3.2.0-beta0.)

`vite-plugin-electron@0.10.0` requires at least Vite@3.2.0

**Comment by caoxiemeihao** [comment]
> The change to cjs format

If you need to use cjs format then you need to set option `nodeIntegrationInWorker: true`

image

**Comment by astoilkov** [comment]
Sorry, I didn't understand that, but no worries, I will check it myself.

**Comment by caoxiemeihao** [comment]
> The change to cjs format

These will be the default behavior of Vite.

- `nodeIntegration: true` will change `output.format='cjs'`
```js
await import('./path')
↓
await Promise.resolve(require('./path'))
```

- `nodeIntegration: false`
```js
await import('./path')
↓
await import('./path')
```

> Worker change

`{ type: 'module' }` has no effect on Vite's build behavior.

**Comment by caoxiemeihao** [comment]
@astoilkov Hi! 👋 My good friend.

```ts
export default {
  plugins: [
    renderer({
      resolve(dependencies) {
        return dependencies
      },
      nodeIntegration: true,
    }),
  ],
  worker: {
    plugins: [
      worker({
        resolve(dependencies) {
          return dependencies
        },
        nodeIntegrationInWorker: true,
      }),
    ],
  },
}

```

**Pull request merged**
