### PR TITLE
V0.20.0

### PR DESCRIPTION
**Pull request by caoxiemeihao**
In flighting 🚀

- [x] vite@5
- [ ] electron@28 + esm

### CODE REVIEW

**Comment by Stanzilla** [comment]
Is 0.15.5 okay to use with Electron 28 or should we wait with upgrading to 28 until 0.20 is ready?

**Comment by caoxiemeihao** [comment]
> Is 0.15.5 okay to use with Electron 28 or should we wait with upgrading to 28 until 0.20 is ready?

Of course, but `v0.28.0-beta.1` is out! you can see the [Migration to v0.28.0-beta.1](aa).

**Comment by Stanzilla** [comment]
> > Is 0.15.5 okay to use with Electron 28 or should we wait with upgrading to 28 until 0.20 is ready?
> 
> Of course, but `v0.28.0-beta.1` is out! you can see the [Migration to v0.28.0-beta.1](https://github.com/electron-vite/vite-plugin-electron/blob/v0.28.0-beta.1/CHANGELOG.md?rgh-link-date=2023-12-30T05%3A53%3A51Z#migration-to-v0280-beta1).

started looking into this now, noticed the upgrade guide is missing the info that you also have to rename the entry for the preload script to mjs otherwise great, thank you! working through more errors here which are probably in dependencies

**Comment by caoxiemeihao** [comment]
For preload scripts, electron@28 still has [some limitations](https://github.com/electron/electron/blob/v30.0.0-nightly.20231218/docs/tutorial/esm.md#preload-scripts), and the `.mjs` file suffix must be used to enable `esm` support.
However, electron officially recommends building preload scripts into a bundle file. It seems that supporting `esm` has little impact on preload scripts.

I will update `0.28.0-beta.2` to continue optimizing `esm` support.

**Comment by caoxiemeihao** [comment]
[v0.28.0-beta.2](https://github.com/electron-vite/vite-plugin-electron/pull/192) is out!

**Pull request merged**
